#Just Some Announcements
print('|YOOOOOOO|' +'\n|   lil  |'+'\n|* notice|')
print('Issa \nJ.S.A')
print('J.ust' + '\nS.ome' + '\nA.nnouncemnts')
print('*Its been a while since I updated the Github playlist.\n\t Honestly for good reason.')
print('*****There\'s....\n\t!!!!!NEW THINGS ON THE WAY!!!!!')
print('On the road to web3\n JavaScrpit creeping soon|Kno HTML right behind it|')
print('\tHey maybe even the preview of a game.')
print('    ??    ')
print(' ??Maybe? A Pokemon\slash DD? Game??')
print('    ??     ')
print('\t\t  ||But!!||')
print('\t\t------------')
print('||Stay tuned for some more announcements!!! :)||')
